/** @type {import('jest').Config} */
module.exports = {
  verbose: true,
  testEnvironment: 'node',
  testMatch: ['**/tests/**/*.test.js', '**/tests/**/*.test.ts'],
  // Ignore known-broken / duplicate / not-yet-migrated legacy test folders
  testPathIgnorePatterns: [
    '/node_modules/',
    '/tests/olga/',
    '/tests/empty-blockqoute/',
    '/tests/edge-cases-advanced.test.js',
    '/tests/integration/full-content.test.js',
    '/tests/tags/',
    '/tests/lists/',
    '/tests/blockquote/',
    '/tests/br/',
    '/tests/code/',
    '/tests/del/',
    '/tests/em/',
    '/tests/empty-ol/',
    '/tests/empty-ul/',
    '/tests/header/',
    '/tests/hr/',
    '/tests/image/',
    '/tests/link/',
    '/tests/ol-list/',
    '/tests/paragraph/',
    '/tests/q/',
    '/tests/recipe/',
    '/tests/strong/',
    '/tests/ul-list/',
  ],
  moduleNameMapper: {
    '^markdown-regex$': '<rootDir>/dist/index.cjs',
  },
  transform: {},
  collectCoverageFrom: ['src/**/*.{ts,js}', '!src/**/*.d.ts'],
  coverageThreshold: {
    global: {
      branches: 30,
      functions: 30,
      lines: 30,
      statements: 30,
    },
  },
};
